(() => ({
  name: 'Breadcrumbs',
  icon: 'BreadcrumbIcon',
  category: 'NAVIGATION',
  keywords: ['Navigation', 'bread', 'crumb'],
  structure: [
    {
      name: 'Breadcrumbs',
      options: [
        {
          label: 'Max Items',
          key: 'maxItems',
          value: '0',
          type: 'CUSTOM',
          configuration: {
            as: 'DROPDOWN',
            dataType: 'string',
            allowedInput: [
              { name: 'All', value: '0' },
              { name: '1', value: '1' },
              { name: '2', value: '2' },
              { name: '3', value: '3' },
              { name: '4', value: '4' },
              { name: '5', value: '5' },
              { name: '6', value: '6' },
              { name: '7', value: '7' },
              { name: '8', value: '8' },
              { name: '9', value: '9' },
              { name: '10', value: '10' },
            ],
          },
        },
        {
          label: 'Items before collapse',
          key: 'itemsBeforeCollapse',
          value: '1',
          type: 'CUSTOM',
          configuration: {
            as: 'DROPDOWN',
            dataType: 'string',
            allowedInput: [
              { name: '1', value: '1' },
              { name: '2', value: '2' },
              { name: '3', value: '3' },
              { name: '4', value: '4' },
              { name: '5', value: '5' },
              { name: '6', value: '6' },
              { name: '7', value: '7' },
              { name: '8', value: '8' },
              { name: '9', value: '9' },
              { name: '10', value: '10' },
            ],
            condition: {
              type: 'HIDE',
              option: 'maxItems',
              comparator: 'EQ',
              value: '0',
            },
          },
        },
        {
          label: 'Items after collapse',
          key: 'itemsAfterCollapse',
          value: '1',
          type: 'CUSTOM',
          configuration: {
            as: 'DROPDOWN',
            dataType: 'string',
            allowedInput: [
              { name: '1', value: '1' },
              { name: '2', value: '2' },
              { name: '3', value: '3' },
              { name: '4', value: '4' },
              { name: '5', value: '5' },
              { name: '6', value: '6' },
              { name: '7', value: '7' },
              { name: '8', value: '8' },
              { name: '9', value: '9' },
              { name: '10', value: '10' },
            ],
            condition: {
              type: 'HIDE',
              option: 'maxItems',
              comparator: 'EQ',
              value: '0',
            },
          },
        },
        {
          label: 'Separator Type',
          key: 'separatorType',
          value: 'text',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Text', value: 'text' },
              { name: 'Icon', value: 'icon' },
            ],
          },
        },
        {
          type: 'TEXT',
          label: 'Separator Text',
          key: 'separatorText',
          value: '/',
          configuration: {
            condition: {
              type: 'SHOW',
              option: 'separatorType',
              comparator: 'EQ',
              value: 'text',
            },
          },
        },
        {
          label: 'Separator Icon',
          key: 'separatorIcon',
          value: 'ChevronRight',
          type: 'ICON',
          configuration: {
            condition: {
              type: 'SHOW',
              option: 'separatorType',
              comparator: 'EQ',
              value: 'icon',
            },
          },
        },
        {
          value: false,
          label: 'Advanced settings',
          key: 'advancedSettings',
          type: 'TOGGLE',
        },
        {
          type: 'VARIABLE',
          label: 'Test attribute',
          key: 'dataComponentAttribute',
          value: ['Breadcrumbs'],
          configuration: {
            condition: {
              type: 'SHOW',
              option: 'advancedSettings',
              comparator: 'EQ',
              value: true,
            },
          },
        },
      ],
      descendants: [
        {
          name: 'BreadcrumbItem',
          options: [
            {
              type: 'VARIABLE',
              label: 'Content',
              key: 'breadcrumbContent',
              value: ['Breadcrumb Item'],
            },
            {
              type: 'ENDPOINT',
              label: 'Page',
              key: 'endpoint',
              value: '',
            },
            {
              type: 'COLOR',
              label: 'Text color',
              key: 'textColor',
              value: 'Black',
            },
            {
              label: 'Icon',
              key: 'icon',
              value: 'None',
              type: 'ICON',
            },
            {
              type: 'CUSTOM',
              label: 'Icon position',
              key: 'iconPosition',
              value: 'start',
              configuration: {
                as: 'BUTTONGROUP',
                dataType: 'string',
                condition: {
                  type: 'HIDE',
                  option: 'variant',
                  comparator: 'EQ',
                  value: 'icon',
                },
                allowedInput: [
                  { name: 'Start', value: 'start' },
                  { name: 'End', value: 'end' },
                ],
              },
            },
            {
              value: false,
              label: 'Advanced settings',
              key: 'advancedSettings',
              type: 'TOGGLE',
            },
            {
              type: 'VARIABLE',
              label: 'Test attribute',
              key: 'dataComponentAttribute',
              value: ['BreadcrumbItem'],
              configuration: {
                condition: {
                  type: 'SHOW',
                  option: 'advancedSettings',
                  comparator: 'EQ',
                  value: true,
                },
              },
            },
          ],
          descendants: [],
        },
        {
          name: 'BreadcrumbItem',
          options: [
            {
              type: 'VARIABLE',
              label: 'Content',
              key: 'breadcrumbContent',
              value: ['Breadcrumb Item'],
            },
            {
              type: 'ENDPOINT',
              label: 'Page',
              key: 'endpoint',
              value: '',
            },
            {
              type: 'COLOR',
              label: 'Text color',
              key: 'textColor',
              value: 'Black',
            },
            {
              label: 'Icon',
              key: 'icon',
              value: 'None',
              type: 'ICON',
            },
            {
              type: 'CUSTOM',
              label: 'Icon position',
              key: 'iconPosition',
              value: 'start',
              configuration: {
                as: 'BUTTONGROUP',
                dataType: 'string',
                condition: {
                  type: 'HIDE',
                  option: 'variant',
                  comparator: 'EQ',
                  value: 'icon',
                },
                allowedInput: [
                  { name: 'Start', value: 'start' },
                  { name: 'End', value: 'end' },
                ],
              },
            },
            {
              value: false,
              label: 'Advanced settings',
              key: 'advancedSettings',
              type: 'TOGGLE',
            },
            {
              type: 'VARIABLE',
              label: 'Test attribute',
              key: 'dataComponentAttribute',
              value: ['BreadcrumbItem'],
              configuration: {
                condition: {
                  type: 'SHOW',
                  option: 'advancedSettings',
                  comparator: 'EQ',
                  value: true,
                },
              },
            },
          ],
          descendants: [],
        },
      ],
    },
  ],
}))();
