(() => ({
  name: 'DataTable',
  icon: 'DataTable',
  category: 'DATA',
  structure: [
    {
      name: 'DataTable',
      options: [
        {
          value: '',
          label: 'Model',
          key: 'model',
          type: 'MODEL',
        },
        {
          value: '',
          label: 'Authentication Profile',
          key: 'authProfile',
          type: 'AUTHENTICATION_PROFILE',
        },
        {
          value: {},
          label: 'Filter',
          key: 'filter',
          type: 'FILTER',
          configuration: {
            dependsOn: 'model',
          },
        },
        {
          value: '',
          label: 'Default order',
          key: 'orderProperty',
          type: 'PROPERTY',
          configuration: {
            dependsOn: 'model',
            apiVersion: 'v1',
          },
        },
        {
          value: 'asc',
          label: 'Sort order',
          key: 'sortOrder',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Ascending', value: 'asc' },
              { name: 'Descending', value: 'desc' },
            ],
            condition: {
              type: 'HIDE',
              option: 'orderProperty',
              comparator: 'EQ',
              value: '',
            },
          },
        },
        {
          value: '',
          label: 'Search on property',
          key: 'searchProperty',
          type: 'PROPERTY',
          configuration: {
            dependsOn: 'model',
            apiVersion: 'v1',
          },
        },
        {
          value: '',
          label: 'Hide built-in search field',
          key: 'hideSearch',
          type: 'TOGGLE',
        },
        {
          type: 'VARIABLE',
          label: 'Title',
          key: 'title',
          value: [''],
        },
        {
          value: 'Title4',
          label: 'Title type',
          key: 'titleType',
          type: 'FONT',
        },
        {
          label: 'Pagination',
          key: 'pagination',
          value: 'always',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Always', value: 'always' },
              { name: 'When needed', value: 'whenNeeded' },
              { name: 'Never', value: 'never' },
            ],
          },
        },
        {
          value: '5',
          label: 'Rows per page',
          key: 'take',
          type: 'CUSTOM',
          configuration: {
            as: 'DROPDOWN',
            dataType: 'string',
            allowedInput: [
              { name: '5', value: '5' },
              { name: '10', value: '10' },
              { name: '25', value: '25' },
              { name: '50', value: '50' },
              { name: '100', value: '100' },
            ],
            condition: {
              type: 'HIDE',
              option: 'pagination',
              comparator: 'EQ',
              value: 'never',
            },
          },
        },
        {
          type: 'VARIABLE',
          label: 'Rows per page text',
          key: 'labelRowsPerPage',
          value: ['Rows per page'],
          configuration: {
            condition: {
              type: 'HIDE',
              option: 'pagination',
              comparator: 'EQ',
              value: 'never',
            },
          },
        },
        {
          type: 'TOGGLE',
          label: 'Sticky header',
          key: 'stickyHeader',
          value: false,
        },
        {
          type: 'SIZE',
          label: 'Height',
          key: 'height',
          value: '',
          configuration: {
            as: 'UNIT',
            condition: {
              type: 'SHOW',
              option: 'stickyHeader',
              comparator: 'EQ',
              value: true,
            },
          },
        },
        {
          value: 'medium',
          label: 'Size',
          key: 'size',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Small', value: 'small' },
              { name: 'Medium', value: 'medium' },
            ],
          },
        },
        {
          type: 'COLOR',
          label: 'Background',
          key: 'background',
          value: 'Transparent',
        },
        {
          type: 'COLOR',
          label: 'Background header',
          key: 'backgroundHeader',
          value: 'Transparent',
        },
        {
          label: 'Square',
          key: 'square',
          value: false,
          type: 'TOGGLE',
        },
        {
          label: 'Variant',
          key: 'variant',
          value: 'elevation',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Flat', value: 'flat' },
              { name: 'Elevation', value: 'elevation' },
              { name: 'Outlined', value: 'outlined' },
            ],
          },
        },
        {
          label: 'Elevation',
          key: 'elevation',
          value: '1',
          type: 'CUSTOM',
          configuration: {
            as: 'DROPDOWN',
            dataType: 'string',
            allowedInput: [
              { name: '1', value: '1' },
              { name: '2', value: '2' },
              { name: '3', value: '3' },
              { name: '4', value: '4' },
              { name: '5', value: '5' },
              { name: '6', value: '6' },
              { name: '7', value: '7' },
              { name: '8', value: '8' },
              { name: '9', value: '9' },
              { name: '10', value: '10' },
              { name: '11', value: '11' },
              { name: '12', value: '12' },
              { name: '13', value: '13' },
              { name: '14', value: '14' },
              { name: '15', value: '15' },
              { name: '16', value: '16' },
              { name: '17', value: '17' },
              { name: '18', value: '18' },
              { name: '19', value: '19' },
              { name: '20', value: '20' },
              { name: '21', value: '21' },
              { name: '22', value: '22' },
              { name: '23', value: '23' },
              { name: '24', value: '24' },
            ],
            condition: {
              type: 'SHOW',
              option: 'variant',
              comparator: 'EQ',
              value: 'elevation',
            },
          },
        },
        {
          value: '',
          label: 'Row click',
          key: 'linkTo',
          type: 'ENDPOINT',
        },
        {
          type: 'COLOR',
          label: 'Row hover color',
          key: 'backgroundRowHover',
          value: 'Transparent',
          configuration: {
            condition: {
              type: 'HIDE',
              option: 'linkTo',
              comparator: 'EQ',
              value: '',
            },
          },
        },
        {
          value: ['0rem', '0rem', 'M', '0rem'],
          label: 'Outer space',
          key: 'outerSpacing',
          type: 'SIZES',
        },
        {
          value: 'built-in',
          label: 'Error message',
          key: 'showError',
          type: 'CUSTOM',
          configuration: {
            as: 'BUTTONGROUP',
            dataType: 'string',
            allowedInput: [
              { name: 'Built in', value: 'built-in' },
              { name: 'Interaction', value: 'interaction' },
            ],
          },
        },
      ],
      descendants: [
        {
          name: 'DataTableColumn',
          options: [
            {
              value: '',
              label: 'Property',
              key: 'property',
              type: 'PROPERTY',
            },
            {
              type: 'TOGGLE',
              label: 'Sortable',
              key: 'sortable',
              value: false,
            },
            {
              type: 'VARIABLE',
              label: 'Header text',
              key: 'headerText',
              value: [''],
            },
            {
              value: 'Body1',
              label: 'Header Type',
              key: 'type',
              type: 'FONT',
            },
            {
              type: 'VARIABLE',
              label: 'Content',
              key: 'content',
              value: [''],
              configuration: {
                as: 'MULTILINE',
              },
            },
            {
              value: 'Body1',
              label: 'Body type',
              key: 'bodyType',
              type: 'FONT',
            },
            {
              type: 'CUSTOM',
              label: 'Column Alignment',
              key: 'horizontalAlignment',
              value: 'left',
              configuration: {
                as: 'BUTTONGROUP',
                dataType: 'string',
                allowedInput: [
                  { name: 'Left', value: 'left' },
                  { name: 'Center', value: 'center' },
                  { name: 'Right', value: 'right' },
                ],
              },
            },
            {
              type: 'SIZE',
              label: 'Width',
              key: 'width',
              value: '',
              configuration: {
                as: 'UNIT',
              },
            },
            {
              type: 'COLOR',
              label: 'Background',
              key: 'background',
              value: 'Transparent',
            },
            {
              type: 'COLOR',
              label: 'Border color',
              key: 'borderColor',
              value: 'Light',
            },
          ],
          descendants: [],
        },
        {
          name: 'DataTableColumn',
          options: [
            {
              value: '',
              label: 'Property',
              key: 'property',
              type: 'PROPERTY',
            },
            {
              type: 'TOGGLE',
              label: 'Sortable',
              key: 'sortable',
              value: false,
            },
            {
              type: 'VARIABLE',
              label: 'Header text',
              key: 'headerText',
              value: [''],
            },
            {
              value: 'Body1',
              label: 'Header Type',
              key: 'type',
              type: 'FONT',
            },
            {
              type: 'VARIABLE',
              label: 'Content',
              key: 'content',
              value: [''],
              configuration: {
                as: 'MULTILINE',
              },
            },
            {
              value: 'Body1',
              label: 'Body type',
              key: 'bodyType',
              type: 'FONT',
            },
            {
              type: 'CUSTOM',
              label: 'Column Alignment',
              key: 'horizontalAlignment',
              value: 'left',
              configuration: {
                as: 'BUTTONGROUP',
                dataType: 'string',
                allowedInput: [
                  { name: 'Left', value: 'left' },
                  { name: 'Center', value: 'center' },
                  { name: 'Right', value: 'right' },
                ],
              },
            },
            {
              type: 'SIZE',
              label: 'Width',
              key: 'width',
              value: '',
              configuration: {
                as: 'UNIT',
              },
            },
            {
              type: 'COLOR',
              label: 'Background',
              key: 'background',
              value: 'Transparent',
            },
            {
              type: 'COLOR',
              label: 'Border color',
              key: 'borderColor',
              value: 'Light',
            },
          ],
          descendants: [],
        },
      ],
    },
  ],
}))();
