name: Publish component set on test environments

on:
  push:
    branches:
      - edge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install packages
        run: bun install

      - name: build
        run: bun run build

      - name: bundle
        run: bun run bundle

      - name: upload
        env:
          AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_EDGE }}
          AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_EDGE }}
        run: bun run upload
