name: Publish bundle.js to acceptance

on:
  workflow_dispatch:

jobs:
  deploy_bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.5
      - name: Install packages
        run: yarn install

      - name: bundle
        run: yarn bundle

      - name: upload
        env:
          AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_ACCEPTANCE }}
          AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_ACCEPTANCE }}
        run: yarn upload-bundle
