name: Material UI testing and linting

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install packages
        run: bun install

      - name: Lint
        run: bun run lint:ci
      - name: Build test
        run: |
          bun run bundle
          bun run build
