name: Material UI testing and linting

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: yarn install
      
    - name: Lint
      run: yarn lint
    - name: Build test  
      run: |
        yarn bundle
        yarn build
